# data.py
# Author: Brian Li
# Genres
genres_very_positive = ["action", "adventure", "comedy", "family", "fantasy", "musical", "romance"]
genres_positive = ["adventure", "game-show", "fantasy", "sport"]
genres_neutral = ["biography", "documentary", "news", "talk-show", "western"]
genres_negative = ["mystery", "crime", "film-noir", "thriller"]
genres_very_negative = ["adult", "crime", "horror", "film-noir", "thriller", "war"]

# Movie Database
movie_database = [
    {"title": "The Shawshank Redemption", "genre": "drama", "rating": 9.3, "length": 142},
    {"title": "The Godfather", "genre": "crime", "rating": 9.2, "length": 175},
    {"title": "The Dark Knight", "genre": "action", "rating": 9.0, "length": 152},
    {"title": "The Godfather Part II", "genre": "crime", "rating": 9.0, "length": 202},
    {"title": "12 Angry Men", "genre": "drama", "rating": 9.0, "length": 96},
    {"title": "Schindler's List", "genre": "biography", "rating": 9.0, "length": 195},
    {"title": "The Lord of the Rings: The Return of the King", "genre": "fantasy", "rating": 8.9, "length": 201},
    {"title": "Pulp Fiction", "genre": "crime", "rating": 8.9, "length": 154},
    {"title": "The Lord of the Rings: The Fellowship of the Ring", "genre": "fantasy", "rating": 8.8, "length": 178},
    {"title": "Forrest Gump", "genre": "drama", "rating": 8.8, "length": 142},
    {"title": "Inception", "genre": "action", "rating": 8.8, "length": 148},
    {"title": "The Lord of the Rings: The Two Towers", "genre": "fantasy", "rating": 8.7, "length": 179},
    {"title": "Star Wars: Episode V - The Empire Strikes Back", "genre": "action", "rating": 8.7, "length": 124},
    {"title": "The Matrix", "genre": "action", "rating": 8.7, "length": 136},
    {"title": "Goodfellas", "genre": "crime", "rating": 8.7, "length": 146},
    {"title": "One Flew Over the Cuckoo's Nest", "genre": "drama", "rating": 8.7, "length": 133},
    {"title": "Seven Samurai", "genre": "action", "rating": 8.6, "length": 207},
    {"title": "Interstellar", "genre": "adventure", "rating": 8.6, "length": 169},
    {"title": "The Silence of the Lambs", "genre": "thriller", "rating": 8.6, "length": 118},
    {"title": "Saving Private Ryan", "genre": "war", "rating": 8.6, "length": 169},
    {"title": "City of God", "genre": "crime", "rating": 8.6, "length": 130},
    {"title": "Life Is Beautiful", "genre": "comedy", "rating": 8.6, "length": 116},
    {"title": "The Green Mile", "genre": "drama", "rating": 8.6, "length": 189},
    {"title": "Se7en", "genre": "crime", "rating": 8.6, "length": 127},
    {"title": "The Usual Suspects", "genre": "crime", "rating": 8.5, "length": 106},
    {"title": "Léon: The Professional", "genre": "action", "rating": 8.5, "length": 110},
    {"title": "The Lion King", "genre": "family", "rating": 8.5, "length": 88},
    {"title": "Spirited Away", "genre": "animation", "rating": 8.5, "length": 125},
    {"title": "American History X", "genre": "drama", "rating": 8.5, "length": 119},
    {"title": "The Departed", "genre": "crime", "rating": 8.5, "length": 151},
    {"title": "The Prestige", "genre": "drama", "rating": 8.5, "length": 130},
    {"title": "Gladiator", "genre": "action", "rating": 8.5, "length": 155},
    {"title": "Whiplash", "genre": "drama", "rating": 8.5, "length": 106},
    {"title": "The Pianist", "genre": "biography", "rating": 8.5, "length": 150},
    {"title": "Parasite", "genre": "thriller", "rating": 8.5, "length": 132},
    {"title": "The Intouchables", "genre": "biography", "rating": 8.5, "length": 112},
    {"title": "Terminator 2: Judgment Day", "genre": "action", "rating": 8.5, "length": 137},
    {"title": "Back to the Future", "genre": "adventure", "rating": 8.5, "length": 116},
    {"title": "Raiders of the Lost Ark", "genre": "adventure", "rating": 8.4, "length": 115},
    {"title": "The Shining", "genre": "horror", "rating": 8.4, "length": 146},
    {"title": "Joker", "genre": "crime", "rating": 8.4, "length": 122},
    {"title": "The Lives of Others", "genre": "drama", "rating": 8.4, "length": 137},
    {"title": "The Great Dictator", "genre": "comedy", "rating": 8.4, "length": 125},
    {"title": "Avengers: Infinity War", "genre": "action", "rating": 8.4, "length": 149},
    {"title": "Aliens", "genre": "action", "rating": 8.4, "length": 137},
    {"title": "Amélie", "genre": "comedy", "rating": 8.4, "length": 122},
    {"title": "Once Upon a Time in the West", "genre": "western", "rating": 8.4, "length": 165},
    {"title": "Coco", "genre": "animation", "rating": 8.4, "length": 105},
    {"title": "Django Unchained", "genre": "western", "rating": 8.4, "length": 165},
    {"title": "The Hunt", "genre": "drama", "rating": 8.4, "length": 115},
    {"title": "WALL·E", "genre": "animation", "rating": 8.4, "length": 98},
    {"title": "The Wolf of Wall Street", "genre": "biography", "rating": 8.4, "length": 180},
    {"title": "The Sixth Sense", "genre": "drama", "rating": 8.4, "length": 107},
    {"title": "A Beautiful Mind", "genre": "biography", "rating": 8.4, "length": 135},
    {"title": "No Country for Old Men", "genre": "crime", "rating": 8.4, "length": 122},
    {"title": "The Truman Show", "genre": "comedy", "rating": 8.4, "length": 103},
    {"title": "There Will Be Blood", "genre": "drama", "rating": 8.4, "length": 158},
    {"title": "Gone with the Wind", "genre": "drama", "rating": 8.4, "length": 238},
    {"title": "The Big Lebowski", "genre": "comedy", "rating": 8.4, "length": 117},
    {"title": "The Thing", "genre": "horror", "rating": 8.4, "length": 109},
    {"title": "Fargo", "genre": "crime", "rating": 8.4, "length": 98},
    {"title": "The Grand Budapest Hotel", "genre": "comedy", "rating": 8.4, "length": 99},
    {"title": "Blade Runner 2049", "genre": "sci-fi", "rating": 8.4, "length": 164},
    {"title": "The Deer Hunter", "genre": "drama", "rating": 8.4, "length": 183},
    {"title": "The Revenant", "genre": "adventure", "rating": 8.4, "length": 156},
    {"title": "Casablanca", "genre": "drama", "rating": 8.4, "length": 102},
    {"title": "Oldboy", "genre": "action", "rating": 8.4, "length": 120},
    {"title": "The Wizard of Oz", "genre": "adventure", "rating": 8.4, "length": 102},
    {"title": "The Sting", "genre": "crime", "rating": 8.4, "length": 129},
    {"title": "The Bridge on the River Kwai", "genre": "adventure", "rating": 8.4, "length": 161},
    {"title": "The Third Man", "genre": "film-noir", "rating": 8.4, "length": 104},
    {"title": "The Elephant Man", "genre": "biography", "rating": 8.4, "length": 124},
    {"title": "The Maltese Falcon", "genre": "film-noir", "rating": 8.4, "length": 100},
    {"title": "The Apartment", "genre": "comedy", "rating": 8.4, "length": 125},
    {"title": "The Treasure of the Sierra Madre", "genre": "adventure", "rating": 8.4, "length": 126},
    {"title": "The Best Years of Our Lives", "genre": "drama", "rating": 8.4, "length": 172},
    {"title": "The General", "genre": "action", "rating": 8.4, "length": 78},
    {"title": "The Gold Rush", "genre": "comedy", "rating": 8.4, "length": 95},
    {"title": "The Kid", "genre": "comedy", "rating": 8.4, "length": 68},
    {"title": "Modern Times", "genre": "comedy", "rating": 8.4, "length": 87},
    {"title": "City Lights", "genre": "comedy", "rating": 8.4, "length": 87},
    {"title": "Metropolis", "genre": "sci-fi", "rating": 8.4, "length": 153},
    {"title": "Sunrise: A Song of Two Humans", "genre": "drama", "rating": 8.4, "length": 94},
    {"title": "The Passion of Joan of Arc", "genre": "biography", "rating": 8.4, "length": 82},
    {"title": "Nosferatu", "genre": "horror", "rating": 8.4, "length": 94},
    {"title": "Battleship Potemkin", "genre": "drama", "rating": 8.4, "length": 75},
    {"title": "The Cabinet of Dr. Caligari", "genre": "horror", "rating": 8.4, "length": 76},
    {"title": "Man with a Movie Camera", "genre": "documentary", "rating": 8.4, "length": 68},
    {"title": "Sherlock Jr.", "genre": "comedy", "rating": 8.4, "length": 45},
    {"title": "The Last Laugh", "genre": "drama", "rating": 8.4, "length": 77},
    {"title": "The Crowd", "genre": "drama", "rating": 8.4, "length": 98},
    {"title": "The Circus", "genre": "comedy", "rating": 8.4, "length": 72},
    {"title": "The Wind", "genre": "drama", "rating": 8.4, "length": 95},
    {"title": "The Docks of New York", "genre": "drama", "rating": 8.4, "length": 76},
    {"title": "The Man Who Laughs", "genre": "drama", "rating": 8.4, "length": 110},
    {"title": "The Phantom of the Opera", "genre": "horror", "rating": 8.4, "length": 93},
    {"title": "The Hunchback of Notre Dame", "genre": "drama", "rating": 8.4, "length": 117},
    {"title": "The Golem", "genre": "horror", "rating": 8.4, "length": 85},
    {"title": "The Birth of a Nation", "genre": "drama", "rating": 8.4, "length": 190},
    {"title": "Intolerance", "genre": "drama", "rating": 8.4, "length": 197},
    {"title": "The General", "genre": "action", "rating": 8.4, "length": 78},
    {"title": "The Gold Rush", "genre": "comedy", "rating": 8.4, "length": 95},
    {"title": "The Kid", "genre": "comedy", "rating": 8.4, "length": 68},
    {"title": "Modern Times", "genre": "comedy", "rating": 8.4, "length": 87},
    {"title": "City Lights", "genre": "comedy", "rating": 8.4, "length": 87},
    {"title": "Metropolis", "genre": "sci-fi", "rating": 8.4, "length": 153},
    {"title": "Sunrise: A Song of Two Humans", "genre": "drama", "rating": 8.4, "length": 94},
    {"title": "The Passion of Joan of Arc", "genre": "biography", "rating": 8.4, "length": 82},
    {"title": "Nosferatu", "genre": "horror", "rating": 8.4, "length": 94},
    {"title": "Battleship Potemkin", "genre": "drama", "rating": 8.4, "length": 75},
    {"title": "The Cabinet of Dr. Caligari", "genre": "horror", "rating": 8.4, "length": 76},
    {"title": "Man with a Movie Camera", "genre": "documentary", "rating": 8.4, "length": 68},
    {"title": "Sherlock Jr.", "genre": "comedy", "rating": 8.4, "length": 45},
    {"title": "The Last Laugh", "genre": "drama", "rating": 8.4, "length": 77},
    {"title": "The Crowd", "genre": "drama", "rating": 8.4, "length": 98},
    {"title": "The Circus", "genre": "comedy", "rating": 8.4, "length": 72},
    {"title": "The Wind", "genre": "drama", "rating": 8.4, "length": 95},
    {"title": "The Docks of New York", "genre": "drama", "rating": 8.4, "length": 76},
    {"title": "The Man Who Laughs", "genre": "drama", "rating": 8.4, "length": 110},
    {"title": "The Phantom of the Opera", "genre": "horror", "rating": 8.4, "length": 93},
    {"title": "The Hunchback of Notre Dame", "genre": "drama", "rating": 8.4, "length": 117},
    {"title": "The Golem", "genre": "horror", "rating": 8.4, "length": 85},
    {"title": "The Birth of a Nation", "genre": "drama", "rating": 8.4, "length": 190},
    {"title": "Intolerance", "genre": "drama", "rating": 8.4, "length": 197},
    {"title": "The General", "genre": "action", "rating": 8.4, "length": 78},
    {"title": "The Gold Rush", "genre": "comedy", "rating": 8.4, "length": 95},
    {"title": "The Kid", "genre": "comedy", "rating": 8.4, "length": 68},
    {"title": "Modern Times", "genre": "comedy", "rating": 8.4, "length": 87},
    {"title": "City Lights", "genre": "comedy", "rating": 8.4, "length": 87}
    ]